### ISSUE TITLE
Example for python usage?

### ISSUE THREAD

**Issue by spto** [user29A/fastrometry#1]
How to call fastrometry in a Python script?

Thank you!

**Comment by user29A** [comment]
Please read the Wiki here:

https://github.com/user29A/fastrometry/wiki/Usage-and-Options

From the command prompt, after installation you simply need to go:

fastrometry -filename value -scale value -ra value -dec value

Inside a script, you would need to import:

from fastrometry import findWCS

and call findWCS(...)
