### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'int' but got 'long'

### ISSUE THREAD

**Issue by chazshapiro** [user29A/fastrometry#3]
Hello, I keep getting the error below.  Could you please advise?  The example FITS file is from SDSS.

Thanks,
CS

```
$ fastrometry frame-g-000756-3-0095.fits -ra "RA" -dec "DEC" -scale 0.4
.
.
.
Extracting sources from image...
Traceback (most recent call last):
  File "/home/developer/.conda/envs/ngpsdev/bin/fastrometry", line 8, in <module>
    sys.exit(callFromCommandLine())
  File "/home/developer/.conda/envs/ngpsdev/lib/python3.10/site-packages/fastrometry/fastrometry.py", line 885, in callFromCommandLine
    solution = findWCS(args.filename, ra=args.ra, dec=args.dec, scale=args.scale, scalebnds=args.scalebnds, rotation=args.rotation, rotationbnds=args.rotationbnds, buffer=args.buffer, fieldshape=args.fieldshape, catalogue=args.catalogue, filter=args.filter, pmepoch=args.pmepoch, npts=args.npts, nrefinepts=args.nrefinepts, pixsat=args.pixsat, kernelrad=args.kernelrad, sourcesep=args.sourcesep, vertextol=args.vertextol, nmatchpoints=args.nmatchpoints, nmatchpercent=args.nmatchpercent, wcsdiagnostics=args.wcsdiagnostics, overwrite=args.overwrite, save=args.save, load=args.load, verbosity=args.verbosity, debug=args.debug)
  File "/home/developer/.conda/envs/ngpsdev/lib/python3.10/site-packages/fastrometry/fastrometry.py", line 784, in findWCS
    num_psesources = PSE(img, img_xmax, img_ymax, kernelrad, sourcesep, pixsat, npts, nrefinepts, pixelradius, fieldshape, srcindexmap_initial, srcindexmap_refine, pse_metadata, debug_report, filepath, debug, verbosity)
  File "src\fastrometry\cython_code\PSE.pyx", line 515, in fastrometry.cython_code.PSE.PSE
ValueError: Buffer dtype mismatch, expected 'int' but got 'long'

```

**Comment by user29A** [comment]
Would you please provide the FITS file "frame-g-000756-3-0095.fits" - just via online drive or something.

Thanks!

**Comment by chazshapiro** [comment]
Sure thing:  https://dr12.sdss.org/sas/dr12/boss/photoObj/frames/301/756/3/frame-g-000756-3-0095.fits.bz2

**Comment by user29A** [comment]
That image shows as vertically inverted on my machine. It wouldn't solve as is, but if I inverted it vertically, then it solved instantaneously on CCDLAB. Here is the FITS file with vertical inversion:

https://drive.google.com/file/d/1C4_YGQH8yH7crbF159F3N3DXXlFyJoYF/view?usp=share_link

I also had to change the -ra and -dec to "CRVAL1" and "CRVAL2" when solving in CCDLAB, as it seems that the default RA and DEC are off a bit - the image center needs to be a bit more precise - yes the RA & DEC are actually 0.6 degrees off from the CRVAL, which is a few times wider than the field of view.

Strangely, when I try to solve with fastrometry, I get no errors, but it doesn't solve, even when specifying CRVAL, and when that file name is the inverted one.

fastrometry frame-g-000756-3-0095.fits -ra "CRVAL1" -dec "CRVAL2" -scale 0.4

Try downloading that inverted file (link above), and use the line above, and see what happens. Let me know results.

**Comment by chazshapiro** [comment]
Thanks for looking into it.  With the inverted file and the new command, I get the same error as in my original post.  Could you point me to a FITS file (and command) that is confirmed to work?

**Comment by user29A** [comment]
What OS are you using for this? We did not test at all on Mac, and very little on Linux.

With this file:

https://drive.google.com/file/d/1Il3kuAgRdO7jnbf3jY-XJ8S4z-zMFJaV/view?usp=share_link

running this works for me:

fastrometry LMC-75_FUV_Silica_31609_0000265684432_deFPN_deDIST_deDrift_IMAGE_x8_deFlat_deExp20.fits -ra "RA_PNT" -dec "DEC_PNT" -scale 0.416

Let me know the OS you're on and I'll get the main developer to see if he can solve the problem after looking at the error you're reporting. It looks like for some reason some internal argument isn't being passed around at a consistent precision, which for some reason only manifests as an error on your OS, as it works with no error on my machine. Thanks!

**Comment by chazshapiro** [comment]
Same error on that file and command.  I'm on Linux RHEL 8.  Thank you very much.

**Comment by cam92473** [comment]
Hi Chaz and Joe,

Let me get back to you in about a week or so. I am booked at the moment but
I will keep a tab on this issue. I have a linux machine so I'll see if I
can get it working on that.

Regards,

Cameron

**Comment by chazshapiro** [comment]
Hi Cameron - any update?

**Comment by cam92473** [comment]
Hi Chaz,

Thanks for being so patient. I have been really busy but I had a look at
the problem now on my Linux Mint. I get the exact same error, so I would
guess that this issue occurs on linux systems in general. I will
investigate this over the weekend (or sooner if possible) and try to
resolve this. Thanks for reporting this issue.

Cameron

**Comment by chazshapiro** [comment]
Thanks for looking into it

**Comment by cam92473** [comment]
Hi Chaz,

I think I was able to fix your issue. It seems on Linux that some datatypes
are handled differently than on windows. I made some adjustments and it now
works on my Linux. Let me know if it works for you.

Cameron

**Comment by chazshapiro** [comment]
It worked!  Looking forward to experimenting.  Thank you very much.

**Comment by user29A** [comment]
Excellent!
